# Generated by Django 5.0.2 on 2024-03-28 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Web-dev', 'Web-dev'), ('Machine Learning', 'Machine Learning')], default='Web-dev', max_length=160, null=True)),
                ('image', models.ImageField(upload_to='blog_image/')),
            ],
        ),
    ]
