# Generated by Django 5.0.2 on 2024-03-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('secret_key', models.CharField(max_length=50)),
                ('valid_until', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
