# Generated by Django 5.0.2 on 2024-03-08 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0002_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="firstapp",
        ),
    ]
