# Generated by Django 5.0.2 on 2024-03-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_education_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_picture',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
