# Generated by Django 5.0.2 on 2024-03-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0004_userdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetail",
            name="request_approved",
            field=models.BooleanField(default=False),
        ),
    ]
