# Generated by Django 5.0.2 on 2024-03-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0006_remove_userdetail_request_approved_userdetail_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
