# Generated by Django 5.0.2 on 2024-03-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0007_alter_userdetail_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="status",
            field=models.CharField(max_length=50),
        ),
    ]
