# Generated by Django 5.0.2 on 2024-03-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0010_userdetail_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="note",
            field=models.TextField(),
        ),
    ]
