# Generated by Django 5.0.2 on 2024-03-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("service_icon", models.CharField(max_length=50)),
                ("service_title", models.CharField(max_length=50)),
                ("service_des", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
